In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Rainfall data for the year 2016.csv')
df = df.drop(['Date'], axis = 1)
df.head()

,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches
0,74,60,45,67,49,43,93,75,57,29.86,29.68,29.59,10,7,2,20,4,31,0.46
1,56,48,39,43,36,28,93,68,43,30.41,30.13,29.87,10,10,5,16,6,25,0
2,58,45,32,31,27,23,76,52,27,30.56,30.49,30.41,10,10,10,8,3,12,0
3,61,46,31,36,28,21,89,56,22,30.56,30.45,30.30,10,10,7,12,4,20,0
4,58,50,41,44,40,36,86,71,56,30.41,30.33,30.27,10,10,7,10,2,16,T

In [4]:
df = df.replace('T', 0.0)
df = df.replace('-', 0.0)
df.head()

,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches
0,74,60,45,67,49,43,93,75,57,29.86,29.68,29.59,10,7,2,20,4,31,0.46
1,56,48,39,43,36,28,93,68,43,30.41,30.13,29.87,10,10,5,16,6,25,0
2,58,45,32,31,27,23,76,52,27,30.56,30.49,30.41,10,10,10,8,3,12,0
3,61,46,31,36,28,21,89,56,22,30.56,30.45,30.30,10,10,7,12,4,20,0
4,58,50,41,44,40,36,86,71,56,30.41,30.33,30.27,10,10,7,10,2,16,0

In [5]:
print(df.values[0])

[74 60 45 '67' '49' '43' '93' '75' '57' 29.86 29.68 29.59 '10' '7' '2' 20
 4 31 '0.46']

In [6]:
df.to_csv('1.csv', index = False)

In [7]:
for i in range(335,364):
    print(i, end=',')

335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,

In [8]:
df = df.drop(df.index[[335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363]])
df.head()

,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches
0,74,60,45,67,49,43,93,75,57,29.86,29.68,29.59,10,7,2,20,4,31,0.46
1,56,48,39,43,36,28,93,68,43,30.41,30.13,29.87,10,10,5,16,6,25,0
2,58,45,32,31,27,23,76,52,27,30.56,30.49,30.41,10,10,10,8,3,12,0
3,61,46,31,36,28,21,89,56,22,30.56,30.45,30.30,10,10,7,12,4,20,0
4,58,50,41,44,40,36,86,71,56,30.41,30.33,30.27,10,10,7,10,2,16,0

In [9]:
print(df.values[0])

[74 60 45 '67' '49' '43' '93' '75' '57' 29.86 29.68 29.59 '10' '7' '2' 20
 4 31 '0.46']

In [10]:
mm = df['PrecipitationSumInches']
mm = [float(i) * 25.4 for i in mm]

In [11]:
df = df.drop(['PrecipitationSumInches'], axis = 1)

In [12]:
df['Rainfallmm'] = mm
df.head()

,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,Rainfallmm
0,74,60,45,67,49,43,93,75,57,29.86,29.68,29.59,10,7,2,20,4,31,11.684
1,56,48,39,43,36,28,93,68,43,30.41,30.13,29.87,10,10,5,16,6,25,0.000
2,58,45,32,31,27,23,76,52,27,30.56,30.49,30.41,10,10,10,8,3,12,0.000
3,61,46,31,36,28,21,89,56,22,30.56,30.45,30.30,10,10,7,12,4,20,0.000
4,58,50,41,44,40,36,86,71,56,30.41,30.33,30.27,10,10,7,10,2,16,0.000

In [13]:
df.head(20)

,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,Rainfallmm
0,74,60,45,67,49,43,93,75,57,29.86,29.68,29.59,10,7,2,20,4,31,11.684
1,56,48,39,43,36,28,93,68,43,30.41,30.13,29.87,10,10,5,16,6,25,0.000
2,58,45,32,31,27,23,76,52,27,30.56,30.49,30.41,10,10,10,8,3,12,0.000
3,61,46,31,36,28,21,89,56,22,30.56,30.45,30.30,10,10,7,12,4,20,0.000
4,58,50,41,44,40,36,86,71,56,30.41,30.33,30.27,10,10,7,10,2,16,0.000
5,57,48,39,39,36,33,79,63,47,30.47,30.40,30.34,10,9,7,12,3,17,0.000
6,60,53,45,41,39,37,83,65,47,30.46,30.39,30.34,10,9,7,7,1,11,0.000
7,62,51,40,43,39,33,92,64,36,30.33,30.17,30.04,10,10,7,10,2,14,0.000
8,64,50,36,49,41,28,92,76,60,30.31,30.10,29.99,10,10,4,17,5,24,0.000
9,44,40,35,31,26,21,75,60,45,30.44,30.33,30.26,10,10,10,13,5,21,0.000
10,55,46,36,31,28,23,76,54,32,30.49,30.39,30.27,10,10,10,8,1,12,0.000
11,69,54,39,51,42,30,83,68,52,30.25,30.11,30.01,10,10,8,13,4,22,0.000
12,55,44,33,39,26,19,83,55,26,30.49,30.37,30.15,10,10,9,21,8,31,0.000
13,58,43,28,37,22,18,75,49,22,30.48,30.35,30.14,10,10,10,14,4,21,0.000
14,71,57,42,55,48,38,89,68,47,30.12,29.95,29.81,10,10,8,16,7,28,0.000
15,59,47,34,54,32,15,87,59,31,30.48,30.08,29.79,10,10,4,21,10,34,0.000
16,36,29,22,15,8,2,50,38,26,30.80,30.68,30.50,10,10,10,17,7,27,0.000
17,48,35,22,29,11,4,68,43,17,30.66,30.52,30.36,10,10,10,13,5,22,0.000
18,53,47,40,51,45,30,93,75,57,30.33,30.20,30.12,10,2,1,12,1,18,4.064
19,70,62,53,60,55,50,93,80,66,30.18,30.11,30.00,10,4,0,12,3,19,0.000

In [14]:
print(df.values[0])

[74 60 45 '67' '49' '43' '93' '75' '57' 29.86 29.68 29.59 '10' '7' '2' 20
 4 31 11.684]

In [15]:
df.to_csv('1.csv', index = False)

In [16]:
import sklearn as sk
from sklearn.linear_model import LinearRegression as LR

In [17]:
training_data = df.drop(['Rainfallmm'], axis = 1)
labels = df['Rainfallmm']

In [18]:
print(training_data.values[0])

[74 60 45 '67' '49' '43' '93' '75' '57' 29.86 29.68 29.59 '10' '7' '2' 20
 4 31]

In [19]:
print(training_data)

     TempHighF  TempAvgF  TempLowF DewPointHighF DewPointAvgF DewPointLowF  \
0           74        60        45            67           49           43
1           56        48        39            43           36           28
2           58        45        32            31           27           23
3           61        46        31            36           28           21
4           58        50        41            44           40           36
..         ...       ...       ...           ...          ...          ...
330         50        42        34            49           45           28
331         53        42        30            27           21           14
332         56        43        30            27           23           19
333         69        51        33            45           38           23
334         70        57        44            63           57           43

    HumidityHighPercent HumidityAvgPercent HumidityLowPercent  \
0                    93                 75                 57
1                    93                 68                 43
2                    76                 52                 27
3                    89                 56                 22
4                    86                 71                 56
..                  ...                ...                ...
330                 100                 91                 82
331                  82                 52                 22
332                  78                 51                 24
333                  86                 64                 42
334                 100                 85                 70

     SeaLevelPressureHighInches  SeaLevelPressureAvgInches  \
0                         29.86                      29.68
1                         30.41                      30.13
2                         30.56                      30.49
3                         30.56                      30.45
4                         30.41                      30.33
..                          ...                        ...
330                       30.25                      30.00
331                       30.50                      30.40
332                       30.57                      30.48
333                       30.40                      30.27
334                       30.17                      30.08

     SeaLevelPressureLowInches VisibilityHighMiles VisibilityAvgMiles  \
0                        29.59                  10                  7
1                        29.87                  10                 10
2                        30.41                  10                 10
3                        30.30                  10                 10
4                        30.27                  10                 10
..                         ...                 ...                ...
330                      29.92                  10                  4
331                      30.25                  10                 10
332                      30.42                  10                 10
333                      30.17                  10                 10
334                      30.02                  10                  8

    VisibilityLowMiles  WindHighMPH  WindAvgMPH  WindGustMPH
0                    2           20           4           31
1                    5           16           6           25
2                   10            8           3           12
3                    7           12           4           20
4                    7           10           2           16
..                 ...          ...         ...          ...
330                  0           17           6           28
331                 10           16           6           26
332                  3           10           2           15
333                 10           13           3           22
334                  0           12           3           16

[335 rows x 18 columns]

In [20]:
print(labels)

0      11.684
1       0.000
2       0.000
3       0.000
4       0.000
        ...
330     0.254
331     0.000
332     0.000
333     0.000
334     0.254
Name: Rainfallmm, Length: 335, dtype: float64

In [21]:
model = LR()

In [22]:
model.fit(training_data, labels)

LinearRegression()

In [23]:
init_df = pd.read_csv('Rainfall data for the year 2016.csv')
init_df=init_df.drop(['Date', 'PrecipitationSumInches'], axis = 1)
init_df.head(337)

,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH
0,74,60,45,67,49,43,93,75,57,29.86,29.68,29.59,10,7,2,20,4,31
1,56,48,39,43,36,28,93,68,43,30.41,30.13,29.87,10,10,5,16,6,25
2,58,45,32,31,27,23,76,52,27,30.56,30.49,30.41,10,10,10,8,3,12
3,61,46,31,36,28,21,89,56,22,30.56,30.45,30.30,10,10,7,12,4,20
4,58,50,41,44,40,36,86,71,56,30.41,30.33,30.27,10,10,7,10,2,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332,56,43,30,27,23,19,78,51,24,30.57,30.48,30.42,10,10,3,10,2,15
333,69,51,33,45,38,23,86,64,42,30.40,30.27,30.17,10,10,10,13,3,22
334,70,57,44,63,57,43,100,85,70,30.17,30.08,30.02,10,8,0,12,3,16
335,74,68,62,69,65,62,100,90,79,30.12,30.05,29.99,10,6,0,13,5,20
336,67,63,58,64,62,56,100,97,93,30.07,29.86,29.70,10,6,0,20,7,28

In [24]:
init_df.to_csv('2.csv', index = False)

In [25]:
init_df = pd.read_csv('2.csv')
print(init_df.values[0])

[74 60 45 '67' '49' '43' '93' '75' '57' 29.86 29.68 29.59 '10' '7' '2' 20
 4 31]

In [26]:
df1 = pd.read_csv('1.csv')
print(df1.values[0])

[74.    60.    45.    67.    49.    43.    93.    75.    57.    29.86
 29.68  29.59  10.     7.     2.    20.     4.    31.    11.684]

In [27]:
print(init_df.values[157])

[73 68 63 '67' '64' '61' '93' '86' '79' 30.03 29.95 29.86 '10' '6' '0' 22
 3 31]

In [28]:
inp = np.array([[74], [68], [62], [69], [65], [62], [100], [90], [79], [30.12], [30.05], [29.99], [10], [6], [0], [13], [5], [20]]) 
inp = inp.reshape(1, -1) 
print(model.predict(inp))

[12.9467503]

In [ ]:
	Date	TempHighF	TempAvgF	TempLowF	DewPointHighF	DewPointAvgF	DewPointLowF	HumidityHighPercent	HumidityAvgPercent	HumidityLowPercent	SeaLevelPressureHighInches	SeaLevelPressureAvgInches	SeaLevelPressureLowInches	VisibilityHighMiles	VisibilityAvgMiles	VisibilityLowMiles	WindHighMPH	WindAvgMPH	WindGustMPH	PrecipitationSumInches	Events
1077	2016-12-01	69	53	37	43	34	31	85	56	27	30.16	30.08	30.01	10	10	10	12	3	16	0