In [119]:
import pandas as pd
import sklearn as sk
import numpy as np

In [120]:
df = pd.read_csv('Rainfall data for the year 2016.csv')
df.head()

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches
0,01-01-2016,74,60,45,67,49,43,93,75,57,29.86,29.68,29.59,10,7,2,20,4,31,0.46
1,02-01-2016,56,48,39,43,36,28,93,68,43,30.41,30.13,29.87,10,10,5,16,6,25,0
2,03-01-2016,58,45,32,31,27,23,76,52,27,30.56,30.49,30.41,10,10,10,8,3,12,0
3,04-01-2016,61,46,31,36,28,21,89,56,22,30.56,30.45,30.30,10,10,7,12,4,20,0
4,05-01-2016,58,50,41,44,40,36,86,71,56,30.41,30.33,30.27,10,10,7,10,2,16,T

In [121]:
df = df.replace('T', 0)
df = df.replace('-', 0)

In [122]:
df.head()

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches
0,01-01-2016,74,60,45,67,49,43,93,75,57,29.86,29.68,29.59,10,7,2,20,4,31,0.46
1,02-01-2016,56,48,39,43,36,28,93,68,43,30.41,30.13,29.87,10,10,5,16,6,25,0
2,03-01-2016,58,45,32,31,27,23,76,52,27,30.56,30.49,30.41,10,10,10,8,3,12,0
3,04-01-2016,61,46,31,36,28,21,89,56,22,30.56,30.45,30.30,10,10,7,12,4,20,0
4,05-01-2016,58,50,41,44,40,36,86,71,56,30.41,30.33,30.27,10,10,7,10,2,16,0

In [123]:
df = df.drop('Date', axis = 1)
df.head()

,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches
0,74,60,45,67,49,43,93,75,57,29.86,29.68,29.59,10,7,2,20,4,31,0.46
1,56,48,39,43,36,28,93,68,43,30.41,30.13,29.87,10,10,5,16,6,25,0
2,58,45,32,31,27,23,76,52,27,30.56,30.49,30.41,10,10,10,8,3,12,0
3,61,46,31,36,28,21,89,56,22,30.56,30.45,30.30,10,10,7,12,4,20,0
4,58,50,41,44,40,36,86,71,56,30.41,30.33,30.27,10,10,7,10,2,16,0

In [124]:
df.shape

(364, 19)

In [125]:
list_hrs = []
for i in range(0, 364):
    list_hrs.append(i*24)
print(len(list_hrs))

364

In [126]:
df['hrs'] = list_hrs
df.head(336)

,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches,hrs
0,74,60,45,67,49,43,93,75,57,29.86,29.68,29.59,10,7,2,20,4,31,0.46,0
1,56,48,39,43,36,28,93,68,43,30.41,30.13,29.87,10,10,5,16,6,25,0,24
2,58,45,32,31,27,23,76,52,27,30.56,30.49,30.41,10,10,10,8,3,12,0,48
3,61,46,31,36,28,21,89,56,22,30.56,30.45,30.30,10,10,7,12,4,20,0,72
4,58,50,41,44,40,36,86,71,56,30.41,30.33,30.27,10,10,7,10,2,16,0,96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,53,42,30,27,21,14,82,52,22,30.50,30.40,30.25,10,10,10,16,6,26,0,7944
332,56,43,30,27,23,19,78,51,24,30.57,30.48,30.42,10,10,3,10,2,15,0,7968
333,69,51,33,45,38,23,86,64,42,30.40,30.27,30.17,10,10,10,13,3,22,0,7992
334,70,57,44,63,57,43,100,85,70,30.17,30.08,30.02,10,8,0,12,3,16,0.01,8016
335,74,68,62,69,65,62,100,90,79,30.12,30.05,29.99,10,6,0,13,5,20,Need to predict,8040

In [127]:
print(df.values[0])

[74 60 45 '67' '49' '43' '93' '75' '57' 29.86 29.68 29.59 '10' '7' '2' 20
 4 31 '0.46' 0]

In [128]:
nf = df[335:364]
nf.head()

,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches,hrs
335,74,68,62,69,65,62,100,90,79,30.12,30.05,29.99,10,6,0,13,5,20,Need to predict,8040
336,67,63,58,64,62,56,100,97,93,30.07,29.86,29.70,10,6,0,20,7,28,Need to predict,8064
337,81,67,53,57,48,39,100,62,23,29.84,29.64,29.51,10,10,10,16,5,27,Need to predict,8088
338,66,53,40,39,32,19,76,47,18,30.20,30.06,29.88,10,10,10,15,5,28,Need to predict,8112
339,67,53,38,38,33,25,85,53,20,30.37,30.26,30.20,10,10,10,9,3,16,Need to predict,8136

In [129]:
nf.to_csv('needtopredict.csv', index = False)

In [130]:
df = df.drop(df.index[335:364])
df.shape

(335, 20)

In [131]:
list_col = df.columns
for i in range(0, len(list_col)):
    df[list_col[i]] = df[list_col[i]].astype(float)
print(df.values[0])

[74.   60.   45.   67.   49.   43.   93.   75.   57.   29.86 29.68 29.59
 10.    7.    2.   20.    4.   31.    0.46  0.  ]

In [132]:
df.to_csv('train_data.csv', index = False)

In [133]:
from sklearn.linear_model import LinearRegression as LR

In [134]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range = (-1, 1))

In [135]:
x = df.drop(['PrecipitationSumInches', 'hrs'], axis = 1)
y = df['PrecipitationSumInches']

In [137]:
print(y.values)

[0.46 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.16 0.   0.1  0.   0.01 0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.06 0.05 0.   0.   0.02 0.05 0.   0.   0.
 0.   0.02 0.   0.15 0.   0.   0.   0.   0.   0.   0.1  0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.11 0.   0.
 0.   0.08 0.08 0.17 0.   0.   0.   0.74 0.11 0.01 0.   0.   0.   0.
 0.07 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.01 0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.2  0.27 0.   0.   0.   0.
 0.   0.   1.34 0.   0.   0.06 0.01 0.   0.   0.01 0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.06 0.
 0.   0.   2.45 0.94 0.14 0.   0.   0.   0.   0.   0.   0.   0.   0.19
 0.   0.   1.56 1.75 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.55 0.   0.   1.49 0.   0.   0.   0.   0.   0.02 0.01 0.
 0.   0.   0.27 0.24 0.49 0.01 0.   0.   0.   0.   0.   0.   0.07 0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.06 0.31 3.53 1.52
 0.   0.   0.   0.   0.   0.09 0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.05 0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.07
 0.   0.   0.   0.01 0.   0.98 0.02 0.19 0.22 0.   0.   0.   0.   0.51
 0.68 0.   0.   0.02 0.35 3.66 0.13 0.21 0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.03 0.   0.   0.   0.   0.   0.   0.   0.
 1.42 0.01 0.09 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.3  0.   0.   0.   0.56 1.51 0.04 0.
 0.   0.   0.   0.   0.   0.   0.   0.02 0.01 0.   0.   0.   0.01]

In [112]:
x = x.values
y = y.values

In [138]:
x_train = x[0:300]
y_train = y[0:300]
x_test = x[300:]
y_test = y[300:]
print(len(x_train), len(x_test))

300 35

In [139]:
x_train = scaler.fit_transform(x_train) 
x_test = scaler.fit_transform(x_test)

In [140]:
lr = LR()

In [141]:
lr.fit(x_train, y_train)

LinearRegression()

In [142]:
pre_y = lr.predict(x_test)

In [143]:
pf = pd.DataFrame({'Actual': y_test, 'Predicted': pre_y})
pf.head(35)

     Actual  Predicted
300    0.00   0.258425
301    0.00   0.138049
302    0.00  -0.125318
303    0.00  -0.047343
304    0.00   0.008011
305    0.00  -0.038580
306    0.00  -0.090162
307    0.00  -0.201850
308    0.00  -0.109641
309    0.00   0.099826
310    0.00   0.109690
311    0.00  -0.110593
312    0.00   0.037097
313    0.00  -0.117477
314    0.30   0.519609
315    0.00  -0.253011
316    0.00   0.206002
317    0.00   0.107367
318    0.56   0.741184
319    1.51   0.351478
320    0.04  -0.104259
321    0.00  -0.267417
322    0.00   0.275137
323    0.00  -0.325344
324    0.00   0.239789
325    0.00   0.351148
326    0.00   0.000898
327    0.00   0.120098
328    0.00  -0.297355
329    0.02   0.108347
330    0.01   0.731919
331    0.00   0.152208
332    0.00   0.064360
333    0.00   0.081586
334    0.01   0.368870

In [144]:
print("Accuracy of the model =",lr.score(x_train, y_train))

Accuracy of the model = 0.3154823534584267